### ISSUE TITLE
Can I make my own DIY design based on ESP32-Pico-D4?

### ISSUE THREAD

**Issue by nm17** [gyroflow/flowshutter#151]
The datasheet is available here: https://www.espressif.com/sites/default/files/documentation/esp32-pico-d4_datasheet_en.pdf

Does it have enough built-in flash memory (4MB)? Are there any other concerns regarding using this chip for FlowShutter?

**Comment by DusKing1** [comment]
ESP32 pico d4 works. NeutronRC's SDB is based on this chip
