### ISSUE TITLE
Sony MTP communication problem

### ISSUE THREAD

**Issue by LeonXNBRD** [gyroflow/flowshutter#76]
**Describe the bug**
Handshake with camera but no Master or Slave functionality to start/stop recording.

**Setup and Settings**
- Sony USB mode set to MTP
- 100 kOhm resistor between pin 6 and grnd on multiport
- pin 7 and 8 to respective UART ports on M5

**To Reproduce**

1. Turn on Camera and Flowshutter
2. Plug in Multiport. "Sony remote recognized" popup appears on Flowshutter. No Message on Camera.
3. Pushing record on Camera: Camera records as usual, Flowshutter does nothing
4. Pushing enter button on Flowshutter: Flowshutter stuck in "starting" state, awaits camera response. Camera does nothing.
5. Have to restart Flowshutter as it does not take any commands in this state.

**Comment by LeonXNBRD** [comment]
Issue solved. Now I'm using dedicated UART ports and it works perfekt!

**Comment by LeonXNBRD** [comment]
Reopened because of flowshutter getting locked up when sony is not connected but log is started. Maybe add timeout of a few seconds, when sony does not respond, display error popup and then return to idle screen

**Comment by DusKing1** [comment]
Nice idea, but:
- I designed it this way on purpose because:
    - Users should not expect FlowShutter to work properly if they have the wrong hardware setup/connection
    - When the flowshutter is locked, the user should immediately realize that something is wrong with their settings and should start troubleshooting the hardware. At this point, for Flowshutter, a simple restart can remove Flowshutter's lock.
    - Locking the flowshutter can also avoid the unexpected transmission of other special commands on the uart, such as power off the camera, etc. Although I am not sure about the probability of this situation, this did happen to me once, and I have no way to accurately reproduce this dangerous situation.
- On the other hand, I'm not very confident about writing some kind of timeout code mechanism in asynchronous coroutines. To be honest, asynchronous programming in python has always been my weakness..

**Comment by DusKing1** [comment]
BTW, the FC logging won't start until it receives the "RECORDING" state sent from sony cam, so you'd better check out your hardware setup if you are using the latest master.
